<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\QuickSnip.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyTitle>QuickSnip</AssemblyTitle>
    <Product>QuickSnip for Windows</Product>
    <Description>One-click Windows screenshot capture.</Description>
    <Company>MU-Ali99</Company>
    <Copyright>Copyright © 2026 MU-Ali99</Copyright>
    <Version>0.9.0</Version>
    <FileVersion>0.9.0.0</FileVersion>
    <AssemblyVersion>0.9.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\QuickSnip-source.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" />
  </ItemGroup>
</Project>
